### ISSUE TITLE
Patches not coloured in IE11

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#336] opened 2016-03-22 08:00 UTC
http://www.netlogoweb.org/web?http://m4a-gae-hrd.appspot.com/p/Lye6ouseEv4UIXfFdxYg5_.nlogo

After clicking setup all is fine on Chrome and FireFox but on IE11 I see only the turtles and the patches are white. Windows 7.

**Comment by TheBizzle** [comment] 2016-03-28 04:32
I can't reproduce this one, unfortunately.  It works fine for me in the Edge browser on Windows 10, and I tried running it in IE11 on a Windows 7 VM, but I couldn't replicate the behavior.

I _did_ initially have all *black* patches after `setup` completed, but then the browser in my VM kept working really hard for a couple of minutes, and it eventually produced this:

![screenshot from 2016-03-27 23 23 11](https://cloud.githubusercontent.com/assets/912890/14070974/8f8a72ce-f473-11e5-912a-a4a78cabd35a.png)

Not sure what to say.  For now, I'm closing the issue as "can't reproduce".  I'm happy to reopen the ticket if new instructions come in for reproducing the problem.

**Closed by TheBizzle** 2016-03-28 04:32 UTC
Labels: cant-reproduce

**Comment by ToonTalk** [comment] 2016-03-28 07:23
I can reproduce the problem in IE11 Windows 7 (slightly later version than yours) with

ask patches [set pcolor (list random 255 random 255 random 255)]

Works fine in Chrome and FireFox.

Perhaps it is my graphics card? I'm using a Dell Latitude E7440.

Unlike #257 it works fine with integer values for colors.

**Comment by ToonTalk** [comment] 2016-03-28 07:57
By turning off graphics acceleration I got it to work fine:

![image](https://cloud.githubusercontent.com/assets/2138696/14073675/acc41716-f4fd-11e5-9ca8-176980dff8ad.png)

**Comment by TheBizzle** [comment] 2016-03-28 16:41
Thanks for the extra info.  I'd forgotten about #257.  I've opened #338 to serve as an umbrella issue for these problems that we're seeing from hardware acceleration on your machine.
