### ISSUE TITLE
Arrow heads huge in directed links

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#357] opened 2017-02-11 03:05 UTC
Link Breeds Example looks like this in NetLogo Web:

![image](https://cloud.githubusercontent.com/assets/2138696/22850730/e653b0e8-f049-11e6-87d4-e5938e51a5d0.png)

while the executable looks much better:

![image](https://cloud.githubusercontent.com/assets/2138696/22850736/028a9880-f04a-11e6-8d9f-e0a241c20488.png)

**Comment by TheBizzle** [comment] 2017-02-11 03:07
Yeah, they look absolutely ridiculous.  100% agreed.

However, this is a duplicate of #298.

**Closed by TheBizzle** 2017-02-11 03:07 UTC
Labels: duplicate
