### ISSUE TITLE
"Try to load the model securely" error on NetLogo web for the Ecological Competition Model

### ISSUE THREAD

**Issue by stanleyrhodes** [NetLogo/Galapagos#412] opened 2023-02-12 22:48 UTC
I have an assignment for students in an environment science class that uses the following model to play with competitive exclusion:
http://www.netlogoweb.org/launch#http://ccl.northwestern.edu/netlogo/community/Ecological%20Competition%20Model.nlogo

I've had roughly 350 students use the model in the past couple years without issue, but this year one student got a strange error and I have no idea what to make of it or what to have them do. When they go to the link above, they get this:
![Screenshot_20230203_034313](https://user-images.githubusercontent.com/8390997/218341782-63a16dfc-f4ba-4f30-a33d-2eeed5bae897.png)

They can, however, load a different model from the model library dropdown.

They are using a HP i7 Microsoft OS, and have tried the model on both Microsoft Edge and Google Chrome. 

Is this a known issue? What should I do?

A secondary question that's unrelated to the issue but related to the model is that I think there is a bug in this model that favors species A because species A always gets to eat first sequentially in one of the ask turtles loops. This leads me to ask: what procedure or norm or rule of thumb do we have to correct a model that's on NetLogo web? Sorry for asking here, I'm just not sure where else to ask.

**Comment by LaCuneta** [comment] 2023-02-13 15:09
@stanleyrhodes Sorry you ran into this problem.

So the link is using unsecured HTTP link for netlogoweb.org as well as the model hosted on ccl.northwestern.edu, which is fine (both unsecured), and I confirmed it works for me.  But some browsers or browser plugins auto-redirect unsecured links to a secure URL when available, so https://netlogoweb.org, but they will not similarly update the model link as they won't "see" that part.  Fetching unsecure content (the model) from a secure context (HTTPS) is not allowed.  The fix is to use the HTTPS URL for both:

https://www.netlogoweb.org/launch#https://ccl.northwestern.edu/netlogo/community/Ecological%20Competition%20Model.nlogo

But this issue raises two good points that I'll make sure to get fixed:

1. The error is unreadably small in that box.
2. We do know that ccl.northwestern.edu will use HTTPS/SSL with the default port, so we can go ahead and auto-fix that one up.

> What procedure or norm or rule of thumb do we have to correct a model that's on NetLogo web?

Thanks for thinking of reporting this!  You can either [open an issue in the models library repository](https://github.com/NetLogo/models), or you can email your issue to feedback@ccl.northwestern.edu

**Comment by LaCuneta** [comment] 2023-02-13 18:03
The two issues I noted are now fixed [here](https://github.com/NetLogo/Galapagos/commit/2581b1b6b6676d127109235de67c7cd5b7cb48ae) and [here](https://github.com/NetLogo/Galapagos/commit/64e3a418b3c178ca1ae1f83ace14b8b479d83b7b).

**Closed by LaCuneta** 2023-02-13 18:03 UTC

**Comment by stanleyrhodes** [comment] 2023-02-13 18:08
Thanks LaCuneta. I've sent the link to the student to check that it solves the issue for them.

Indeed, it is a community contributed model. I went to both the NL Web and NL pages to try to find the author, but couldn't find them:
http://www.netlogoweb.org/launch#http://ccl.northwestern.edu/netlogo/community/Ecological%20Competition%20Model.nlogo
https://ccl.northwestern.edu/netlogo/models/community/Ecological%20Competition%20Model

I just realized maybe the full list of models would have a name:
http://ccl.northwestern.edu/netlogo/models/community/

And it does--it's Will Hemsley--but there's no contact information and searching for the name doesn't come up with much. I'll have to make my own version the next time I teach this class.

Thanks for your fixes and super-prompt replies!
