### ISSUE TITLE
world.observer.getGlobal(...) is not a function

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#340] opened 2016-04-18 04:40 UTC
Clicking go in

http://www.netlogoweb.org/web?http://m4a-gae.appspot.com/p/o4m1LekMO1V0fbZrw6iV5a.nlogo

causes this error:

Error
A type error has occurred in the simulation engine. More information about these sorts of errors can be found here.

Advanced users might find the generated error helpful, which is as follows:

world.observer.getGlobal(...) is not a function

**Comment by ToonTalk** [comment] 2016-04-18 04:44
Probably related is I get the error

"x" is not a function

from 

globals [x]

to startup
  set x 5
  user-message runresult "x"
end

**Comment by ToonTalk** [comment] 2016-04-18 04:46
Another problem here is that if one exports the HTML and then clicks on 'here' in

More information about these sorts of errors can be found here.

it is an undefined page.

**Comment by ToonTalk** [comment] 2016-04-18 04:56
The error goes away when I replaced "runresult fire-location" in the code with code that doesn't rely upon runresult.

**Comment by TheBizzle** [comment] 2016-04-18 05:07
I'm going to close this one as a duplicate of NetLogo/Tortoise#122 .  The "A type error has occurred in the simulation engine. More information about these sorts of errors can be found here" message indicates that a prim is receiving an argument that it doesn't know how to handle.  NetLogo/Tortoise#122 explains that `run` and `runresult` don't yet support string arguments.  That is to say that, at the moment, they only accept tasks as arguments.

> Another problem here is that if one exports the HTML and then clicks on 'here' in
> More information about these sorts of errors can be found here.
> it is an undefined page.

Ah, thanks for pointing that out.  I'll make a separate ticket for that.

**Closed by TheBizzle** 2016-04-18 05:07 UTC
