### ISSUE TITLE
Export to nlogo

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/Galapagos#248] opened 2015-06-22 21:11 UTC
Should be able to save NetLogo Web files to nlogo file format.

**Comment by SethTisue** [comment] 2015-06-22 21:26
#189, #193 

(or is that different?)

**Comment by mrerrormessage** [comment] 2015-06-22 22:34
I believe this is a component of #193, but that doing #193 properly would involve more effort than just saving NLW files to the .nlogo file format.

**Comment by mrerrormessage** [comment] 2015-06-23 14:31
I've been working on this, and have it working in principle, but there are a few questions I wanted to discuss around the UI. Find here a screenshot of my current implementation's UI.
![screen shot 2015-06-23 at 8 30 41 am](https://cloud.githubusercontent.com/assets/143198/8308437/4c42e3c6-198a-11e5-8b67-2597a8e0ef2e.png)
I would like some feedback on the UI, and in particular:                                                          
* What is the correct place in the Galpagos UI for the "export to nlogo" button? It seems important enough that we don't want to hide it, but ancillary enough that we don't want to clutter up the main UI with it.
* How do we want to handle filenames? For simplicity, I did the bare minimum and given all downloaded files the name "model.nlogo", testing show that it opens cleanly in NetLogo 5.2. To me, it seems like the best course of action would be to somehow choose a name when they elect to export the file. 
The other alternative is to deduce the file name from the name of the file the user started working from.

**Comment by qiemem** [comment] 2015-06-23 14:53
> What is the correct place in the Galpagos UI for the "export to nlogo" button? It seems important enough that we don't want to hide it, but ancillary enough that we don't want to clutter up the main UI with it.

Next to the compile button perhaps.

> How do we want to handle filenames? For simplicity, I did the bare minimum and given all downloaded files the name "model.nlogo", testing show that it opens cleanly in NetLogo 5.2. To me, it seems like the best course of action would be to somehow choose a name when they elect to export the file. The other alternative is to deduce the file name from the name of the file the user started working from.

Either of those options seem fine to me. We could also have a "name" field somewhere in the UI that the user fills out. Whether we use a persistent name field or a dialogue that comes up on save, I think it should be seeded with the name of the model they started working from.

**Comment by mrerrormessage** [comment] 2015-06-23 14:55
Sounds good. I'll start work on that. If there are other comments, we can discuss further.

**Comment by TheBizzle** [comment] 2015-06-23 15:22
Duplicate of #199.

**Closed by TheBizzle** 2015-06-23 15:22 UTC
