### ISSUE TITLE
Freezing loop

### ISSUE THREAD

**Issue by birbilis** [NetLogo/Galapagos#348] opened 2016-07-19 14:31 UTC
I see generated code of the following style:

  temp = (function() {
    while (MousePrims.isDown()) {
    
    }
    world.observer.setGlobal("dragging?", false);
  });
  procs["waitMouseUp"] = temp;
  procs["WAIT-MOUSE-UP"] = temp;

that causes freezing of Firefox

The compiler should never generate such tight (with no code in them) loops I think if Javascript can't handle them. Should have some small sleep in there. In Java even sleep(0) worked to avoid freezing

**Comment by birbilis** [comment] 2016-07-19 14:33
Please see this screenshot:
![screenshot 2016-07-19 17 24 17](https://cloud.githubusercontent.com/assets/3461504/16953742/e45f66ee-4dd6-11e6-9e3f-55f45cbd1416.png)

**Comment by birbilis** [comment] 2016-07-19 14:43
this correspondes to this code of mine:

to wait-mouse-up
  while [mouse-down?] []
  set dragging? false
end

that works fine in NetLogo Desktop

**Comment by birbilis** [comment] 2016-07-19 15:12
I tried adding a "wait 0" in case it would help, but I get back "Error", "unimplemented primitive: wait" message. What other NOP-style command could I use inside that tight loop?

**Comment by birbilis** [comment] 2016-07-19 17:32
btw, note that Firefox becomes unresponsive even if one presses Stop Script at the respective dialog. You have to press Debug script, then close the tab

**Comment by TheBizzle** [comment] 2016-07-22 21:59
> Should have some small sleep in there. In Java even sleep(0) worked to avoid freezing

There is no such thing in JavaScript, which is a single-threaded environment.  This problem is the same one that prevents `wait` from being implemented.

This problem is on our radar and is something that we want to fix soon.  However, solving these sorts of problems for NetLogo in a general way, in JavaScript, is not straightforward or easy.

Closing as duplicate of NetLogo/Tortoise#151 .

**Closed by TheBizzle** 2016-07-22 21:59 UTC
Labels: duplicate

**Comment by birbilis** [comment] 2016-07-23 00:35
Indeed, had discussed this in the past and had forgotten about it. Would expect the whole netlogo program though to run on a background worker
